

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: api-produto
          uri: lb://api-produto
          predicates:
            - Path=/**
        - id: api-venda
          uri: lb://api-venda
          predicates:
            - Path=/venda/**
        - id: api-usuarios
          uri: lb://api-usuarios
          predicates:
            - Path=/usuarios/**
eureka:
  client:
    serviceUrl:
      registerWithEureka: true
      fetchRegistry: true
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true
    nonSecurePort: 8085
    nonSecurePort-enabled: false
server:
  port: 8085